// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU1Gs2ExkAEujtp97PPkNwLwflXVBEL7k',
    appId: '1:352188565720:web:9a4642be88326bdd0a2fad',
    messagingSenderId: '352188565720',
    projectId: 'tictok-iop',
    authDomain: 'tictok-iop.firebaseapp.com',
    storageBucket: 'tictok-iop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0iJQq2z36aTZBSQ4d0hR5R6S49Tm9bsE',
    appId: '1:352188565720:android:d0f998640aacf8bb0a2fad',
    messagingSenderId: '352188565720',
    projectId: 'tictok-iop',
    storageBucket: 'tictok-iop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3k7V49-YmvRsxtcvu59KVnoJpbIHXefc',
    appId: '1:352188565720:ios:548a4348db63ab400a2fad',
    messagingSenderId: '352188565720',
    projectId: 'tictok-iop',
    storageBucket: 'tictok-iop.appspot.com',
    iosClientId: '352188565720-vitc8v21d9k24plr9lqnosk1f9kq9tnk.apps.googleusercontent.com',
    iosBundleId: 'com.tiktok.tiktokClone',
  );
}
